{"name": "test_one", "status": "skipped", "statusDetails": {"message": "XFAIL reason: 该功能尚未完成\n\n_pytest.outcomes.XFailed: 该功能尚未完成", "trace": "self = <test_Pytest.Test_Pytest object at 0x000001FC7A5147F0>\n\n    @pytest.mark.xfail\n    def test_one(self,):\n            print(\"----start------\")\n>           pytest.xfail(reason='该功能尚未完成')\nE           _pytest.outcomes.XFailed: 该功能尚未完成\n\ntest_Pytest.py:11: XFailed"}, "start": 1628066937345, "stop": 1628066937345, "uuid": "686018ce-3d26-47cb-9634-78e83733df05", "historyId": "97a1eb161c22a41d0473421377dcc4f2", "testCaseId": "85a99274d4e2614f9873f6bf0efdc1f7", "fullName": "test_Pytest.Test_Pytest#test_one", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "suite", "value": "test_Pytest"}, {"name": "subSuite", "value": "Test_Pytest"}, {"name": "host", "value": "MS-GIMBLKWYYOKK"}, {"name": "thread", "value": "16176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_Pytest"}]}